package Reportes;


import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
public class RecoverPasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form RecoverPasswordForm
     */
    public RecoverPasswordForm() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecTop = new javax.swing.JPanel();
        lblTxtPassRec = new javax.swing.JLabel();
        pnlRecBottom = new javax.swing.JPanel();
        lblRecMail = new javax.swing.JLabel();
        lblRecUser = new javax.swing.JLabel();
        txtRecUsername = new javax.swing.JTextField();
        btnRecSend = new javax.swing.JButton();
        txtRecEmail = new javax.swing.JTextField();
        btnRecClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRecTop.setBackground(new java.awt.Color(1, 50, 67));

        lblTxtPassRec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTxtPassRec.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtPassRec.setText("Password Recovery");

        javax.swing.GroupLayout pnlRecTopLayout = new javax.swing.GroupLayout(pnlRecTop);
        pnlRecTop.setLayout(pnlRecTopLayout);
        pnlRecTopLayout.setHorizontalGroup(
            pnlRecTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecTopLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTxtPassRec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRecTopLayout.setVerticalGroup(
            pnlRecTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecTopLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTxtPassRec)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlRecBottom.setBackground(new java.awt.Color(255, 255, 255));

        lblRecMail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/email.png"))); // NOI18N
        lblRecMail.setText("Email Address:");

        lblRecUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reportes/user.png"))); // NOI18N
        lblRecUser.setText("Username:");

        txtRecUsername.setBackground(new java.awt.Color(108, 122, 137));
        txtRecUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRecUsername.setForeground(new java.awt.Color(228, 241, 254));
        txtRecUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecUsernameActionPerformed(evt);
            }
        });

        btnRecSend.setBackground(new java.awt.Color(1, 50, 67));
        btnRecSend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRecSend.setForeground(new java.awt.Color(255, 255, 255));
        btnRecSend.setText("Send");
        btnRecSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecSendActionPerformed(evt);
            }
        });

        txtRecEmail.setBackground(new java.awt.Color(108, 122, 137));
        txtRecEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRecEmail.setForeground(new java.awt.Color(228, 241, 254));
        txtRecEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecEmailActionPerformed(evt);
            }
        });

        btnRecClose.setBackground(new java.awt.Color(1, 50, 67));
        btnRecClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRecClose.setForeground(new java.awt.Color(255, 255, 255));
        btnRecClose.setText("Close");
        btnRecClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRecBottomLayout = new javax.swing.GroupLayout(pnlRecBottom);
        pnlRecBottom.setLayout(pnlRecBottomLayout);
        pnlRecBottomLayout.setHorizontalGroup(
            pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecBottomLayout.createSequentialGroup()
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRecBottomLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecUser)
                            .addComponent(lblRecMail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRecUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRecEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRecBottomLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnRecClose, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecSend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlRecBottomLayout.setVerticalGroup(
            pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecBottomLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecUser))
                .addGap(32, 32, 32)
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRecMail)
                    .addComponent(txtRecEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecClose, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecSend, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRecBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRecTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlRecBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecUsernameActionPerformed

    private void txtRecEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecEmailActionPerformed

    
    private void btnRecSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecSendActionPerformed

      
        JOptionPane.showMessageDialog(this,"Correo enviado.", "Confirmacion",
                                      JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRecSendActionPerformed

    private void btnRecCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecCloseActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRecCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecClose;
    private javax.swing.JButton btnRecSend;
    private javax.swing.JLabel lblRecMail;
    private javax.swing.JLabel lblRecUser;
    private javax.swing.JLabel lblTxtPassRec;
    private javax.swing.JPanel pnlRecBottom;
    private javax.swing.JPanel pnlRecTop;
    private javax.swing.JTextField txtRecEmail;
    private javax.swing.JTextField txtRecUsername;
    // End of variables declaration//GEN-END:variables
}
