package Vista;

import java.awt.Component;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
public class MainMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuForm
     */
    public MainMenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrCuenta = new javax.swing.JButton();
        btnCrProd = new javax.swing.JButton();
        btnCrAlm = new javax.swing.JButton();
        btnCrProv = new javax.swing.JButton();
        btnModCuenta = new javax.swing.JButton();
        btnModProd = new javax.swing.JButton();
        btnModAlm = new javax.swing.JButton();
        btnModProv = new javax.swing.JButton();
        pnlMenuTop = new javax.swing.JPanel();
        lblTextMenu = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/crearCuenta.png"))); // NOI18N
        btnCrCuenta.setText("Crear Cuenta");
        btnCrCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrCuentaActionPerformed(evt);
            }
        });

        btnCrProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/crearProd.png"))); // NOI18N
        btnCrProd.setText("Crear Producto");
        btnCrProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrProdActionPerformed(evt);
            }
        });

        btnCrAlm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrAlm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/almacen.png"))); // NOI18N
        btnCrAlm.setText("Crear Almacen");
        btnCrAlm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrAlmActionPerformed(evt);
            }
        });

        btnCrProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/proveedor.png"))); // NOI18N
        btnCrProv.setText("Crear Proveedor");
        btnCrProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrProvActionPerformed(evt);
            }
        });

        btnModCuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/modificarUser.png"))); // NOI18N
        btnModCuenta.setText("Modificar Cuenta");
        btnModCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCuentaActionPerformed(evt);
            }
        });

        btnModProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/modificar.png"))); // NOI18N
        btnModProd.setText("Modificar Producto");
        btnModProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProdActionPerformed(evt);
            }
        });

        btnModAlm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModAlm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/modificar.png"))); // NOI18N
        btnModAlm.setText("Modificar Almacen");
        btnModAlm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAlmActionPerformed(evt);
            }
        });

        btnModProv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/modificar.png"))); // NOI18N
        btnModProv.setText("Modificar Proveedor");
        btnModProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModProvActionPerformed(evt);
            }
        });

        pnlMenuTop.setBackground(new java.awt.Color(1, 50, 67));

        lblTextMenu.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTextMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblTextMenu.setText("Menu Principal");

        javax.swing.GroupLayout pnlMenuTopLayout = new javax.swing.GroupLayout(pnlMenuTop);
        pnlMenuTop.setLayout(pnlMenuTopLayout);
        pnlMenuTopLayout.setHorizontalGroup(
            pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTopLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTextMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuTopLayout.setVerticalGroup(
            pnlMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuTopLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTextMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/btnSalir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCrProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrAlm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrProv, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addComponent(btnCrCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnModAlm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenuTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModCuenta)
                    .addComponent(btnCrCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrProd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModProd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModAlm)
                    .addComponent(btnCrAlm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrProv)
                    .addComponent(btnModProv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrAlmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrAlmActionPerformed
        NewWrhouseForm nwh = new NewWrhouseForm(this,true);
        nwh.setVisible(true);
    }//GEN-LAST:event_btnCrAlmActionPerformed

    private void btnModCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCuentaActionPerformed
        ModAccountForm maf = new ModAccountForm(this,true);
        maf.setVisible(true);
    }//GEN-LAST:event_btnModCuentaActionPerformed

    private void btnCrCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrCuentaActionPerformed
        NewAccountForm ncf = new NewAccountForm(this, true);
        ncf.setVisible(true);
        
    }//GEN-LAST:event_btnCrCuentaActionPerformed

    private void btnCrProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrProdActionPerformed
        NewProductForm npf = new NewProductForm(this,true);
        npf.setVisible(true);
    }//GEN-LAST:event_btnCrProdActionPerformed

    private void btnModProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProdActionPerformed
        ModProductForm mpf = new ModProductForm(this,true);
        mpf.setVisible(true);
    }//GEN-LAST:event_btnModProdActionPerformed

    private void btnModAlmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAlmActionPerformed
        ModWrhouseForm mwh = new ModWrhouseForm(this,true);
        mwh.setVisible(true);
    }//GEN-LAST:event_btnModAlmActionPerformed

    private void btnCrProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrProvActionPerformed
        NewProveedorForm npf = new NewProveedorForm(this,true);
        npf.setVisible(true);
    }//GEN-LAST:event_btnCrProvActionPerformed

    private void btnModProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModProvActionPerformed
        ModProveedorForm mpf = new ModProveedorForm(this,true);
        mpf.setVisible(true);
    }//GEN-LAST:event_btnModProvActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrAlm;
    private javax.swing.JButton btnCrCuenta;
    private javax.swing.JButton btnCrProd;
    private javax.swing.JButton btnCrProv;
    private javax.swing.JButton btnModAlm;
    private javax.swing.JButton btnModCuenta;
    private javax.swing.JButton btnModProd;
    private javax.swing.JButton btnModProv;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblTextMenu;
    private javax.swing.JPanel pnlMenuTop;
    // End of variables declaration//GEN-END:variables
}
