/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
//import AppPackage.AnimationClass;
import java.awt.Color;
import javafx.stage.Screen;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class MenuGerent extends javax.swing.JFrame {

    /**
     * Creates new form MenuGerent
     */
    public MenuGerent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        btnOpciones = new javax.swing.JButton();
        lblCerrar = new javax.swing.JLabel();
        lblMini = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        txtSistemaAlmacen = new javax.swing.JLabel();
        jPanellateralSuperior = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReportTransf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSuperior.setBackground(new java.awt.Color(16, 164, 211));

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/menu-button-of-three-horizontal-lines-blanco.png"))); // NOI18N
        btnOpciones.setBorder(null);
        btnOpciones.setBorderPainted(false);
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpcionesMouseClicked(evt);
            }
        });
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/minimize.png"))); // NOI18N
        lblMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMiniMouseClicked(evt);
            }
        });

        lblMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/multi-tab.png"))); // NOI18N
        lblMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaxMouseClicked(evt);
            }
        });

        txtSistemaAlmacen.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtSistemaAlmacen.setForeground(java.awt.Color.white);
        txtSistemaAlmacen.setText("Sistema de Almacén LUCET SA");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSistemaAlmacen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1238, Short.MAX_VALUE)
                .addComponent(lblMini)
                .addGap(18, 18, 18)
                .addComponent(lblMax)
                .addGap(18, 18, 18)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMax)
                    .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnOpciones)
                        .addComponent(txtSistemaAlmacen)
                        .addComponent(lblMini, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, -1));

        jPanellateralSuperior.setBackground(new java.awt.Color(64, 64, 64));
        jPanellateralSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAyuda.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnAyuda.setForeground(java.awt.Color.white);
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/groceries.png"))); // NOI18N
        btnAyuda.setText("    Reporte de Stock");
        btnAyuda.setBorder(null);
        btnAyuda.setBorderPainted(false);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanellateralSuperior.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 670, 80));

        btnSalir.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnSalir.setForeground(java.awt.Color.white);
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/question-mark.png"))); // NOI18N
        btnSalir.setText("       Ayuda");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanellateralSuperior.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 670, 80));

        btnReportTransf.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnReportTransf.setForeground(java.awt.Color.white);
        btnReportTransf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/transferir.png"))); // NOI18N
        btnReportTransf.setText("      Reporte de Transferencias");
        btnReportTransf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReportTransf.setContentAreaFilled(false);
        btnReportTransf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportTransf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportTransf.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReportTransf.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReportTransfMouseMoved(evt);
            }
        });
        btnReportTransf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportTransfMouseEntered(evt);
            }
        });
        btnReportTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportTransfActionPerformed(evt);
            }
        });
        jPanellateralSuperior.add(btnReportTransf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 680, 80));

        getContentPane().add(jPanellateralSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, 1870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportTransfActionPerformed
        // TODO add your handling code here:
        frmReporteTransferencias rpf = new frmReporteTransferencias();
         rpf.setVisible(true);
    }//GEN-LAST:event_btnReportTransfActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        // TODO add your handling code here  
    }//GEN-LAST:event_btnOpcionesActionPerformed
        
    private void btnOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcionesMouseClicked
        // TODO add your handling code here:
        int alto,ancho;
        alto=jPanellateralSuperior.getHeight();
        ancho=jPanellateralSuperior.getWidth();
        if(ancho==680){
            jPanellateralSuperior.setSize(50, 1870);
        }
        else{
            jPanellateralSuperior.setSize(680, 1870);
        }        
        //jPanellateralSuperior.setLocationRelativeTo(null);
        jPanellateralSuperior.setLayout(null);       
        jPanellateralSuperior.setVisible(true);
        
    }//GEN-LAST:event_btnOpcionesMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión?","Salir",dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnReportTransfMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportTransfMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnReportTransfMouseMoved

    private void btnReportTransfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportTransfMouseEntered
        // TODO add your handling code here:
         
       
       
    }//GEN-LAST:event_btnReportTransfMouseEntered

    private void lblMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMouseClicked
        // TODO add your handling code here:
        this.setState(MenuGerent.ICONIFIED);
    }//GEN-LAST:event_lblMiniMouseClicked

    private void lblMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaxMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblMaxMouseClicked

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
        frmReporteStock rpf = new frmReporteStock();
         rpf.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGerent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGerent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGerent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGerent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGerent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnReportTransf;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JPanel jPanellateralSuperior;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMini;
    private javax.swing.JLabel txtSistemaAlmacen;
    // End of variables declaration//GEN-END:variables
}
