/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class MenuAdminSist extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdminSist
     */
    public MenuAdminSist() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreSist = new javax.swing.JLabel();
        btnOpciones = new javax.swing.JButton();
        lblMin = new javax.swing.JLabel();
        lblMAx = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jpanelLateral = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnArticulos = new javax.swing.JButton();
        btnAlmacenes = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnUsuarios1 = new javax.swing.JButton();
        btnArticulos1 = new javax.swing.JButton();
        btnAlmacenes1 = new javax.swing.JButton();
        btnProveedores1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 164, 211));

        lblNombreSist.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblNombreSist.setForeground(java.awt.Color.white);
        lblNombreSist.setText("Sistema de Almacén LUCET SA");

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/menu-button-of-three-horizontal-lines-blanco.png"))); // NOI18N
        btnOpciones.setBorderPainted(false);
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpcionesMouseClicked(evt);
            }
        });
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });

        lblMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/minimize.png"))); // NOI18N
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        lblMAx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/multi-tab.png"))); // NOI18N
        lblMAx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/close.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreSist)
                .addGap(18, 18, 18)
                .addComponent(btnOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1317, Short.MAX_VALUE)
                .addComponent(lblMin)
                .addGap(18, 18, 18)
                .addComponent(lblMAx)
                .addGap(15, 15, 15)
                .addComponent(lblCerrar)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCerrar)
                    .addComponent(lblMin)
                    .addComponent(lblMAx)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombreSist)
                            .addComponent(btnOpciones))
                        .addGap(5, 5, 5)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, -1));

        jpanelLateral.setBackground(new java.awt.Color(64, 64, 64));
        jpanelLateral.setMinimumSize(new java.awt.Dimension(680, 631));
        jpanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnUsuarios.setForeground(java.awt.Color.white);
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/user.png"))); // NOI18N
        btnUsuarios.setText("      Modificación de Cuenta");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 588, 53));

        btnArticulos.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnArticulos.setForeground(java.awt.Color.white);
        btnArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/groceries.png"))); // NOI18N
        btnArticulos.setText("       Modificación de Artículos");
        btnArticulos.setBorderPainted(false);
        btnArticulos.setContentAreaFilled(false);
        btnArticulos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnArticulos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 588, -1));

        btnAlmacenes.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnAlmacenes.setForeground(java.awt.Color.white);
        btnAlmacenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/almacen2.png"))); // NOI18N
        btnAlmacenes.setText("       Creación de Almacenes");
        btnAlmacenes.setBorderPainted(false);
        btnAlmacenes.setContentAreaFilled(false);
        btnAlmacenes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlmacenes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenesActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 588, -1));

        btnProveedores.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnProveedores.setForeground(java.awt.Color.white);
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/truck.png"))); // NOI18N
        btnProveedores.setText("       Creación de Proveedores");
        btnProveedores.setBorderPainted(false);
        btnProveedores.setContentAreaFilled(false);
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 588, -1));

        btnUsuarios1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnUsuarios1.setForeground(java.awt.Color.white);
        btnUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/user.png"))); // NOI18N
        btnUsuarios1.setText("      Creación de Cuenta");
        btnUsuarios1.setBorderPainted(false);
        btnUsuarios1.setContentAreaFilled(false);
        btnUsuarios1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios1ActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnUsuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 588, 53));

        btnArticulos1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnArticulos1.setForeground(java.awt.Color.white);
        btnArticulos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/groceries.png"))); // NOI18N
        btnArticulos1.setText("       Creación de Artículos");
        btnArticulos1.setBorderPainted(false);
        btnArticulos1.setContentAreaFilled(false);
        btnArticulos1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnArticulos1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnArticulos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulos1ActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnArticulos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 588, -1));

        btnAlmacenes1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnAlmacenes1.setForeground(java.awt.Color.white);
        btnAlmacenes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/almacen2.png"))); // NOI18N
        btnAlmacenes1.setText("       Modificación de Almacenes");
        btnAlmacenes1.setBorderPainted(false);
        btnAlmacenes1.setContentAreaFilled(false);
        btnAlmacenes1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAlmacenes1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAlmacenes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenes1ActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnAlmacenes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 588, -1));

        btnProveedores1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnProveedores1.setForeground(java.awt.Color.white);
        btnProveedores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menugerente/Imagenes/truck.png"))); // NOI18N
        btnProveedores1.setText("       Modificación de Proveedores");
        btnProveedores1.setBorderPainted(false);
        btnProveedores1.setContentAreaFilled(false);
        btnProveedores1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedores1ActionPerformed(evt);
            }
        });
        jpanelLateral.add(btnProveedores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 870, 588, -1));

        getContentPane().add(jpanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 1400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        ModAccountForm maf = new ModAccountForm(this,true);
        maf.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
         NewProveedorForm npf = new NewProveedorForm(this,true);
        npf.setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        // TODO add your handling code here:
        this.setState(MenuAdminSist.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        int dialog = JOptionPane.YES_NO_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la sesión?","Salir",dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnOpcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcionesMouseClicked
        // TODO add your handling code here:
        int alto,ancho;
        alto=jpanelLateral.getHeight();
        ancho=jpanelLateral.getWidth();
        if(ancho==588){
            jpanelLateral.setSize(50, 1880);
        }
        else{
            jpanelLateral.setSize(588, 1880);
        }        
        //jPanellateralSuperior.setLocationRelativeTo(null);
        jpanelLateral.setLayout(null);       
        jpanelLateral.setVisible(true);
    }//GEN-LAST:event_btnOpcionesMouseClicked

    private void btnUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios1ActionPerformed
        // TODO add your handling code here:
        NewAccountForm ncf = new NewAccountForm(this, true);
        ncf.setVisible(true);
    }//GEN-LAST:event_btnUsuarios1ActionPerformed

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        // TODO add your handling code here:
         ModProductForm mpf = new ModProductForm(this,true);
        mpf.setVisible(true);
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedores1ActionPerformed
        // TODO add your handling code here:
        ModProveedorForm mpf = new ModProveedorForm(this,true);
        mpf.setVisible(true);
    }//GEN-LAST:event_btnProveedores1ActionPerformed

    private void btnArticulos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulos1ActionPerformed
        // TODO add your handling code here:
        NewProductForm npf = new NewProductForm(this,true);
        npf.setVisible(true);
    }//GEN-LAST:event_btnArticulos1ActionPerformed

    private void btnAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenesActionPerformed
        // TODO add your handling code here:
        NewWrhouseForm nwh = new NewWrhouseForm(this,true);
        nwh.setVisible(true);
    }//GEN-LAST:event_btnAlmacenesActionPerformed

    private void btnAlmacenes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenes1ActionPerformed
        // TODO add your handling code here:
        ModWrhouseForm mwh = new ModWrhouseForm(this,true);
        mwh.setVisible(true);
    }//GEN-LAST:event_btnAlmacenes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminSist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminSist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminSist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminSist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdminSist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacenes;
    private javax.swing.JButton btnAlmacenes1;
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnArticulos1;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnProveedores1;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnUsuarios1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpanelLateral;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMAx;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNombreSist;
    // End of variables declaration//GEN-END:variables
}
