package Vista;


import LogicaNegocio.UsuarioBL;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Gerente;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastian
 */
public class RecoverPasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form RecoverPasswordForm
     */
    private UsuarioBL usuarioBL;
    public RecoverPasswordForm() {
        initComponents();
        usuarioBL = new UsuarioBL();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecTop = new javax.swing.JPanel();
        lblTxtPassRec = new javax.swing.JLabel();
        pnlRecBottom = new javax.swing.JPanel();
        lblRecMail = new javax.swing.JLabel();
        btnRecSend = new javax.swing.JButton();
        txtRecEmail = new javax.swing.JTextField();
        btnRecClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlRecTop.setBackground(new java.awt.Color(1, 50, 67));

        lblTxtPassRec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTxtPassRec.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtPassRec.setText("Password Recovery");

        javax.swing.GroupLayout pnlRecTopLayout = new javax.swing.GroupLayout(pnlRecTop);
        pnlRecTop.setLayout(pnlRecTopLayout);
        pnlRecTopLayout.setHorizontalGroup(
            pnlRecTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecTopLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTxtPassRec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRecTopLayout.setVerticalGroup(
            pnlRecTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecTopLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTxtPassRec)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlRecBottom.setBackground(new java.awt.Color(255, 255, 255));

        lblRecMail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRecMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/email.png"))); // NOI18N
        lblRecMail.setText("Correo Electrónico");

        btnRecSend.setBackground(new java.awt.Color(1, 50, 67));
        btnRecSend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRecSend.setForeground(new java.awt.Color(255, 255, 255));
        btnRecSend.setText("Send");
        btnRecSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecSendActionPerformed(evt);
            }
        });

        txtRecEmail.setBackground(new java.awt.Color(108, 122, 137));
        txtRecEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRecEmail.setForeground(new java.awt.Color(228, 241, 254));
        txtRecEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecEmailActionPerformed(evt);
            }
        });

        btnRecClose.setBackground(new java.awt.Color(1, 50, 67));
        btnRecClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRecClose.setForeground(new java.awt.Color(255, 255, 255));
        btnRecClose.setText("Close");
        btnRecClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("¿Olvidó su Contraseña?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Por favor, ingrese su correo electrónico de usuario para enviarle  ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("su nombre de usuario y su contraseña.");

        javax.swing.GroupLayout pnlRecBottomLayout = new javax.swing.GroupLayout(pnlRecBottom);
        pnlRecBottom.setLayout(pnlRecBottomLayout);
        pnlRecBottomLayout.setHorizontalGroup(
            pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecBottomLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnRecClose, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecSend, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(pnlRecBottomLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecBottomLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRecBottomLayout.createSequentialGroup()
                        .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlRecBottomLayout.createSequentialGroup()
                                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlRecBottomLayout.createSequentialGroup()
                                        .addComponent(lblRecMail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRecEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))))
        );
        pnlRecBottomLayout.setVerticalGroup(
            pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecBottomLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecMail)
                    .addComponent(txtRecEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(pnlRecBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecClose, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecSend, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRecBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRecTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRecBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecEmailActionPerformed

    
    private void btnRecSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecSendActionPerformed

      
        //EnviarConGMail("jhloli@pucp.pe", "Prueba", "Mensaje de prueba");
        Gerente usuario = usuarioBL.EnviarCorreo(txtRecEmail.getText());
        JOptionPane.showMessageDialog(this,"Correo enviado.", "Confirmacion",
                                      JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRecSendActionPerformed

    private void btnRecCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecCloseActionPerformed
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRecCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecClose;
    private javax.swing.JButton btnRecSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRecMail;
    private javax.swing.JLabel lblTxtPassRec;
    private javax.swing.JPanel pnlRecBottom;
    private javax.swing.JPanel pnlRecTop;
    private javax.swing.JTextField txtRecEmail;
    // End of variables declaration//GEN-END:variables
}
